Traceback (most recent call last):
  File "main.py", line 18, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
